// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSRrtmyLiEMFvlboXOuaBMn7yaZwI3Lyc',
    appId: '1:106288516521:android:f06e5668ed661a181808b8',
    messagingSenderId: '106288516521',
    projectId: 'mahlete-semay-project',
    storageBucket: 'mahlete-semay-project.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSRrtmyLiEMFvlboXOuaBMn7yaZwI3Lyc',
    appId: '1:106288516521:web:9c849e7bdf1507bc1808b8',
    messagingSenderId: '106288516521',
    projectId: 'mahlete-semay-project',
    authDomain: 'mahlete-semay-project.firebaseapp.com',
    storageBucket: 'mahlete-semay-project.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP9xORcnCXsoXxV2Q1qU1eRoUr9EIfDQY',
    appId: '1:106288516521:ios:8b6c5f94acf0aaab1808b8',
    messagingSenderId: '106288516521',
    projectId: 'mahlete-semay-project',
    storageBucket: 'mahlete-semay-project.firebasestorage.app',
    iosBundleId: 'com.example.mahleteSemayProject',
  );
}
